Improve Ref Docs
adafruit/Adafruit_CircuitPython_LSM9DS0 pull request #3
Opened 2018-03-02 01:06 UTC by sommersoft

[Per Issue #566](https://github.com/adafruit/circuitpython/issues/566)

The following Learn Guide will need the 2 GitHub example code links updated:
https://learn.adafruit.com/adafruit-lsm9ds0-accelerometer-gyro-magnetometer-9-dof-breakouts?view=all#circuitpython-code

2018-03-05 22:21 UTC, kattni requested changes
Thanks for doing this! See inline change requests.

2018-03-05 22:21 UTC, kattni commented on adafruit_lsm9ds0.py
>          m/s^2 values.
"The accelerometer ..." Doesn't need "Returns".

2018-03-05 22:21 UTC, kattni commented on adafruit_lsm9ds0.py
>          gauss values.
Same.

2018-03-05 22:21 UTC, kattni commented on adafruit_lsm9ds0.py
> +        """Returns the gyroscope X, Y, Z axis values as a 3-tuple of
Same.

2018-03-05 22:21 UTC, kattni commented on adafruit_lsm9ds0.py
> +        """Returns the temperature of the sensor in degrees Celsius."""
Same.

2018-03-05 23:10 UTC, sommersoft commented
And here I was thinking "I'll surprise kattni and get these right"... 😄

2018-03-06 00:14 UTC, kattni commented
You're doing a great job! There's obviously a learning curve when you run
into new things. :) You've been picking everything up amazingly! Thank you
again!

On Mon, Mar 5, 2018 at 6:10 PM, sommersoft <notifications@github.com> wrote:

> And here I was thinking "I'll surprise kattni and get these right"... 😄
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/Adafruit_CircuitPython_LSM9DS0/pull/3#issuecomment-370600993>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHgDAmPK8h0Me6Omu7-yHG_QQ0S7KqwCks5tbcXmgaJpZM4SZPrl>
> .
>

2018-03-11 20:05 UTC, kattni approved these changes
Excellent!

2018-03-11 20:05 UTC, merged